all:
	-mkdir output
	g++ permutation1.cpp -o output/permutation1
	g++ permutation2.cpp -o output/permutation2
	g++ permutation3.cpp -o output/permutation3
	g++ permutation4.cpp -o output/permutation4
	g++ permutation_decre.cpp -o output/permutation_decre
	g++ permutation_incre.cpp -o output/permutation_incre


clean:
	rm -rf output
