all:
	-mkdir output
	g++ permutation_dfs.cpp 				-o output/permutation_dfs
	g++ permutation_agency_incre.cpp 		-o output/permutation_agency_incre
	g++ permutation_agency_incre_multi.cpp 	-o output/permutation_agency_incre_multi
	g++ permutation_dict.cpp 				-o output/permutation_dict
	g++ permutation_swap.cpp 				-o output/permutation_swap
	g++ permutation_decre.cpp 				-o output/permutation_decre
	g++ permutation_incre.cpp 				-o output/permutation_incre
	g++ permutation_stl.cpp 				-o output/permutation_stl


clean:
	rm -rf output/
